In [1]:
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [1]:
import numpy as np
mylist = [1,2,3,4,5,6]

x = np.array(mylist * 6)
print(x)
x.resize(6,6)
print(x)
x[::5]
#x.reshape(36)[::7]
#x[0:6,::-7]
#x[:,::7]

#x[2::2,2::2]
#x[::2, ::2]
#x[[2,3],[2,3]]
#x[2:4, 2:4]

[1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6]
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [2]:
m = np.arange(1,37,1)
m.resize(6,6)
print(m)
m[::2]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18],
       [25, 26, 27, 28, 29, 30]])

In [5]:
m1 = m.copy()
m1.reshape(36)[::7]

array([ 1,  8, 15, 22, 29, 36])

In [6]:
m2 = m.copy()
m2[0:6,::-7]

array([[ 6],
       [12],
       [18],
       [24],
       [30],
       [36]])

In [7]:
m3 = m.copy()
m3[:,::7]

array([[ 1],
       [ 7],
       [13],
       [19],
       [25],
       [31]])

In [8]:
m4 = m.copy()
m4[::7]

array([[1, 2, 3, 4, 5, 6]])

In [9]:
n1 = m.copy()
n1[2::2,2::2]

array([[15, 17],
       [27, 29]])

In [11]:
n2 = m.copy()
n2[::2, ::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [12]:
n3 = m.copy()
n3[[2,3],[2,3]]

array([15, 22])

In [13]:
n4 = m.copy()
n4[2:4, 2:4]

array([[15, 16],
       [21, 22]])

In [6]:
y = np.array(mylist)
y[::2]

array([1, 3, 5])

In [12]:
y1 = y.copy()
y1[::7]

array([1])

In [18]:
y2 = y.copy()
y2.resize(3,2)
y2[::7]

array([[1, 2]])